config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'memos#index'
  resources :users, only: [:new, :show]
  resources :memos, only: [:index, :create, :edit, :update, :destroy]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :user
  validates :food, :limit_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :memos

  VALID_EMSIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMSIL_REGEX }, allow_blank: true

  VALID_PASSWORD_REGEX = /\A[a-z0-9]+\z/i
  validates :password, presence: true, length: { minimum: 6 }, format: { with: VALID_PASSWORD_REGEX}, allow_blank: true
  validates :password_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource) 
    user_path(current_user)
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :authenticate_user!, only: [:create, :edit, :update, :destroy]

  def index
    @memos = Memo.includes(:user).order("limit_date")
  end

  def create
    @memo = Memo.new(memo_params)
    if @memo.save
      respond_to do |format|
        # format.html { redirect_to user_path(current_user)}
        format.json
      end
    else
      @user = User.find(params[:id])
      @memos = @user.memos.order("limit_date")
      flash[:alert] = 'メモを入力してください'
      render user_path(current_user)
    end
  end

  def edit
    @memo = Memo.find(params[:id])
  end

  def update
    memo = Memo.find(params[:id])
    memo.update(memo_params)
    if memo.save
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def destroy
    memo = Memo.find(params[:id])
    memo.destroy
    redirect_to user_path(current_user)
  end

  private
  def memo_params
    params.require(:memo).permit(:food, :limit_date).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:new, :show]

  def show
    @memo = Memo.new
    @user = User.find(params[:id])
    @memos = @user.memos.order("limit_date")
  end

  private
  def memo_params
    params.require(:memo).permit(:food, :limit_date).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    =content_tag :div, value, class:key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MemosApp
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    =render 'layouts/notifications'
    = yield

app/views/memos/_edit-form.html.haml
.edit-box
  .title E d i t
  = form_for (@memo) do |f| 
    .form-edit
      .form-edit__food FOOD
      = f.text_field :food, class: 'form-edit__food__name'
      .form-edit__date LIMIT!
      = f.date_select :limit_date, class: 'form-edit__date__limit'
      -# %input{type:"date", class:"formbox__date__limit"}
    .btn
      = f.submit 'Change',class:"edit-btn"

app/views/memos/_left-contents.html.haml
.left-contents
    
  .upper-content
    .title S T O C K
    %form
      .formbox
        .formbox__food FOOD
        %input{type:"text", class:"formbox__food__name", placeholder: " まずは、ログイン"}
        .formbox__date LIMIT!
        %input{type:"date", class:"formbox__date__limit"}
      .btn
        = link_to new_user_registration_path do
          %input{type:"submit", class:"submit-btn", value:"add food"}


  .main-content 
    
    .title-content 
      .title-content__food
        
        Food Name
      .title-content__limit
        Limit Date
          

    .list
      .list__foods
        .list__foods__one 
          = icon('fas','fish')
          バター
        .list__foods__one 
          = icon('fas','fish')
          わさび

      .list__limit
        .list__limit__date
          = icon('fas', 'exclamation-triangle')
          2020-07-01
        .list__limit__date
          = icon('fas', 'exclamation-triangle')
          2020-09-01

      .list__edit
        .list__edit__btn
          変更  
        .list__edit__btn
          変更


      .list__delete
        .list__delete__btn
          終わり
        .list__delete__btn
          終わり

app/views/memos/_right-contents.html.haml
.right-contents
  .title BBB
  .create-buttun ボタン追加(create画面へいくボタン)
  .main-content 
    ここはライトメイン
    .main-content__title-content 
      food limit
    .main-content__body
      ここにメモ一覧

app/views/memos/edit.html.haml
%header
  .header-contents
    .header-contents__title
      .title-box
        Kicchiri Kanri
      .title-memo
        おうちの食材、きちんと管理
      .manage
        .manage-btn
          = link_to user_path(current_user), class: 'manage__btn' do
            マイページ

.main-edit
  = render 'edit-form'

app/views/memos/index.html.haml
%header
  .header-contents
    .header-contents__title
      .title-box
        Kicchiri Kanri
      .title-memo
        おうちの食材、きちんと管理
      .manage
        -# - if user_signed_in?
        -#   .manage-btn
        -#     = link_to user_path(current_user), class: 'manage__btn' do
        -#       マイページへ
        -#   -# .manage-btn
        -#   -#   = link_to new_user_path, class: 'manage__btn' do
        -#   -#     NEW
        -#   -# .manage-btn
        -#   -#   = link_to destroy_user_session_path, method: :delete,  class: 'manege__btn' do
        -#   -#     Log out
        -# - else
        .manage-btn
          = link_to new_user_session_path, class: 'manage__btn' do
            Log in
        .manage-btn
          = link_to new_user_registration_path, class: 'manage__btn' do
            Sing in
%main
  .contents
    = render "left-contents"

app/views/users/_left-contents.html.haml
.left-contents
  .upper-content
    .title S T O C K

    =form_for(@memo) do |f|
      .formbox
        .formbox__food FOOD
        -# = f.label :FOOD, class: 'formbox__food__label'
        = f.text_field :food, class: 'formbox__food__name', placeholder: ' type a food name'
        -# %input{type:"text", class:"formbox__food__name", placeholder: " まずは、ログイン"}
        .formbox__date LIMIT!
        = f.date_select :limit_date, class: 'formbox__date__limit'
      .btn
        = f.submit 'AddFood', class: 'submit-btn'
        -# = link_to new_user_registration_path do
        -#   %input{type:"submit", class:"submit-btn", value:"add food"}

  .main-content 
    
    .title-content 
      .title-content__food
        
        Food Name
      .title-content__limit
        Limit Date
    .list
      .list__foods
        - @memos.each do |memo|
          .list__foods__one 
            = icon('fas','fish')
            = memo.food

      .list__limit
        - @memos.each do |memo|
          .list__limit__date
            = icon('fas', 'exclamation-triangle')
            = memo.limit_date

      .list__edit
        - @memos.each do |memo|
          .list__edit__btn
            =link_to '変更', edit_memo_path(memo)


      .list__delete
        - @memos.each do |memo|
          .list__delete__btn
            = link_to memo_path(memo), method: :delete do
              終わり

app/views/users/show.html.haml
%header
  .header-contents
    .header-contents__title
      .title-box
        Kicchiri Kanri
      .title-memo
        おうちの食材、きちんと管理
      .manage
        - if user_signed_in?
          .manage-btn
            = link_to destroy_user_session_path, method: :delete,  class: 'manege__btn' do
              Log out
        - else
          .manage-btn
            = link_to new_user_session_path, class: 'manage__btn' do
              Log in
          .manage-btn
            = link_to new_user_registration_path, class: 'manage__btn' do
              Sing in
              
%main
  .contents
    = render "left-contents"